### ISSUE TITLE
Brand Icon Request

### ISSUE THREAD

**Issue by LanceMcCarthy** [markusressel/raspyrfm-client#6]
Hi Mark, 

This is a request for an icon that can be used to represent RaspyRFM, to be used in Home Assistant integration. The icon is used in both the Integration's listing, but also [the Integration's documentation](https://www.home-assistant.io/integrations/raspyrfm/).

We want to accurately represent the brand and I was not able to locate any specific iconography. Let me know if there's anything else I can help provide.

Thank you,
Lance

**Comment by markusressel** [comment]
I am not sure I understand your request. The images I used come from https://www.seegel-systeme.de/ which is the store that sells the RaspyRFM module. Afaiknthere is no specific icon for the RaspyRFM module.
